#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2013-2023 Igor Pecovnik, igor@armbian.com
#
# This file is a part of the Armbian Build Framework
# https://github.com/armbian/build/
#
# Important: LINUXFAMILY and ARCH are defined _before_ including the common family include
declare -g LINUXFAMILY="qcom64"
declare -g OVERLAY_DIR="/boot/dtb/qcom/overlay"
declare -g ARCH="arm64"
declare -g BOOTENV_FILE="qcom-abl.txt"
declare -g NETWORKING_STACK="network-manager"
enable_extension "image-output-abl-ufi"

case $BRANCH in

	vendor)
		declare -g KERNEL_MAJOR_MINOR="6.6" # Major and minor versions of this kernel.
		declare -g KERNELBRANCH='tag:v6.6-msm8916'
		declare -g KERNELSOURCE='https://github.com/msm8916-mainline/linux.git'
		declare -g KERNELPATCHDIR="archive/qcom64-6.x"
		declare -g LINUXCONFIG="linux-qcom64-vendor"
		declare -g -i KERNEL_GIT_CACHE_TTL=120 # 2 minutes; this is a high-traffic repo
		;;

	current)
		declare -g KERNEL_MAJOR_MINOR="6.18" # Major and minor versions of this kernel.
		declare -g KERNELPATCHDIR="archive/qcom64-6.x"
		declare -g LINUXCONFIG="linux-qcom64-edge"
		;;

	edge)
		declare -g KERNEL_MAJOR_MINOR="7.0" # Major and minor versions of this kernel.
		declare -g KERNELPATCHDIR="archive/qcom64-7.x"
		declare -g LINUXCONFIG="linux-qcom64-edge"
		;;

esac

family_tweaks_bsp() {
	:
}